print("vvce')
print("mysore")
print("priyanka")
print("anil")
print("DevOps")
print("Software Engineering")
print("new line")
print("line is added")
print("vvce")
print("bangalore123")
print("priya")      
      
